// docs/console-using/spa-demo-vue-feat-refactor/spa-demo-vue-feat-refactor/vue3/src/pages/Callback.vue
<template>
  <div class="callback-container">
    <div>{{ message }}</div>
  </div>
</template>

<script scoped setup>
import { inject, onMounted } from 'vue'
import { useRouter } from 'vue-router'

const router = useRouter()

const $authing = inject('$authing')

const message = 'This is callback page ~'

const handleAuthingLoginCallback = async () => {
  await $authing.enchancedLoginCallback()
  router.replace({
    name: 'Personal'
  })
}

onMounted(() => {
  handleAuthingLoginCallback()
})
</script>

// docs/console-using/spa-demo-react-feat-refactor/spa-demo-react-feat-refactor/src/pages/Callback.jsx
import React, { useEffect } from 'react'
import { useHistory } from 'react-router-dom'

import { useAuthing } from '@/enhance-authing-sdk'

export default function Callback () {
  const history = useHistory()
  const authing = useAuthing()

  const handleCallback = async () => {
    await authing.enchancedLoginCallback()
    history.replace('/personal')
  }

  useEffect(() => {
    handleCallback()
  }, [])

  return <div>This is Callback page</div>
}
