// docs/console-using/spa-demo-angular-feat-refactor/spa-demo-angular-feat-refactor/src/app/pages/login/login.component.ts
import { Component } from '@angular/core'

import { AuthingService } from '../../../enhance-authing-sdk/authing.service'

@Component({
  selector: 'login-container',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  constructor (
    private authing: AuthingService
  ) {}

  userInfo = ''

  ngOnInit () {
    this.getCurrentUser()
  }

  onLogin () {
    this.authing.client.enhancedLogin()
  }

  onLogout () {
    this.authing.client.enhancedLogout()
  }

  async getCurrentUser () {
    const _userInfo = await this.authing.client.getCurrentUser()
    this.userInfo = _userInfo && JSON.stringify(_userInfo, null, 2) || ''
  }
}

// docs/console-using/spa-demo-react-feat-refactor/spa-demo-react-feat-refactor/src/pages/Login.jsx
import React, { useState, useEffect } from 'react'
import { useAuthing } from '@/enhance-authing-sdk'

export default function Login () {
  const [userInfo, setUserInfo] = useState('')
  const authing = useAuthing()

  const getCurrentUser = async () => {
    const _userInfo = await authing.getCurrentUser()
    setUserInfo(_userInfo && JSON.stringify(_userInfo, null, 2) || '')
  }

  useEffect(() => {
    getCurrentUser()
  }, [])

  const onLogin = () => authing.enhancedLogin()
  const onLogout = () => authing.enhancedLogout()

  return <div>
    <div>This is Login page</div>
    {userInfo ? <button onClick={onLogout}>登出</button> : <button onClick={onLogin}>登录</button>}
    {userInfo && <div>
      <div>用户信息：</div>
      <textarea cols="100" rows="30" defaultValue={userInfo}></textarea>
    </div>}
  </div>
}
