// docs/console-using/spa-demo-vue-feat-refactor/spa-demo-vue-feat-refactor/vue3/src/pages/Login.vue
<template>
  <div class="login-container">
    <div style="margin-bottom: 30px;">
      <button v-if="!userInfo" @click="onLogin">登录</button>
      <button v-else @click="onLogout">登出</button>
    </div>

    <div v-if="userInfo">
      <div>用户信息：</div>
      <textarea cols="100" rows="30" :value="userInfo"></textarea>
    </div>
  </div>
</template>

<script setup>
import { inject, ref, onMounted } from 'vue'

const $authing = inject('$authing')
const userInfo = ref('')

const getCurrentUser = async () => {
  const _userInfo = await $authing.getCurrentUser()
  userInfo.value = _userInfo && JSON.stringify(_userInfo, null, 2) || ''
}
const onLogin = () => $authing.enhancedLogin()
const onLogout = () => $authing.enhancedLogout()

onMounted(() => {
  getCurrentUser()
})
</script>

// docs/console-using/spa-demo-react-feat-refactor/spa-demo-react-feat-refactor/src/pages/Login.jsx
import React, { useState, useEffect } from 'react'
import { useAuthing } from '@/enhance-authing-sdk'

export default function Login () {
  const [userInfo, setUserInfo] = useState('')
  const authing = useAuthing()

  const getCurrentUser = async () => {
    const _userInfo = await authing.getCurrentUser()
    setUserInfo(_userInfo && JSON.stringify(_userInfo, null, 2) || '')
  }

  useEffect(() => {
    getCurrentUser()
  }, [])

  const onLogin = () => authing.enhancedLogin()
  const onLogout = () => authing.enhancedLogout()

  return <div>
    <div>This is Login page</div>
    {userInfo ? <button onClick={onLogout}>登出</button> : <button onClick={onLogin}>登录</button>}
    {userInfo && <div>
      <div>用户信息：</div>
      <textarea cols="100" rows="30" defaultValue={userInfo}></textarea>
    </div>}
  </div>
}
